//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDaiDuong_8627_DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string ProductName { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public double Total { get; set; }
        public int IdProduct { get; set; }
        public int IdOrder { get; set; }
    
        public virtual Ordered Ordered { get; set; }
        public virtual Product Product { get; set; }
    }
}
