//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDaiDuong_8627_DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int IdShipper { get; set; }
        public string FullName { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
    }
}
